### ISSUE TITLE
Compliments

### ISSUE THREAD

**Issue by lascellesabercrombie** [fac25/week4-server-side-app-Abby-Patrick-Paz-Yassien#55]
Great job on getting OAuth stuff working! In general, this felt solid and functional.

**Comment by joe-dev-public** [comment]
I second what Alex said - a nice, fun & functional app!

(Heroku deployment was broken when I first tried it, which doesn't really matter because it was working quite well on local. Only tiny problem was that logging in via GitHub redirected to the Heroku deployment even when running from local. Not sure if it's possible to change that (and it wouldn't make a lot of sense to anyway, I guess? :).)

**Comment by Abbbyccc** [comment]
@lascellesabercrombie @joe-dev-public Thank you both from the team!!
